### ISSUE TITLE
Hi, are you still working on this?

### ISSUE THREAD

**Issue by sepsol** [pablouser1/jellyfin-netcast#7]

**Comment by pablouser1** [comment]
Not really, I still have a Netcast TV, but I just use a Raspberry Pi for accessing Jellyfin.

**Comment by sepsol** [comment]
Are you happy with your current setup? If so, I would like to do something similar. Could you please describe your setup and how you're using the Pi?

**Comment by pablouser1** [comment]
Sure, It's a Raspberry Pi 3 running LibreELEC 11.0 with the [Jellyfin for Kodi](https://jellyfin.org/docs/general/clients/kodi/) addon.

For controlling it remotely I use the Kore app, which allows remote control inside the local network.
You could spend some money and get instead an IR Blaster and a TV remote for a smoother expirience I gues, but it's really not necessary

**Comment by sepsol** [comment]
@pablouser1 Thank you very much for the help!
